---
- hosts: localhost
  
  tasks:
  - name: Running mvn install
    shell: "mvn clean install"
    register: mvn_result

  - name: mvn install task output
    debug:
     var: mvn_result

  - name: Log into DockerHub
    docker_login:
      username: brunoguidone
      password: "{{ lookup('env','dockerhub_pass') }}"
      email: brunoguidone@hotmail.com
  
  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: ./
      name: brunoguidone/app-demo
      tag: v1
      push: yes
      source: build

  - name: Create app container
    docker_container:
      name: app-demo
      image: brunoguidone/app-demo:v1
      state: started
      recreate: yes
      ports:
        - 8080:8080
  
  - name: Restart a container
    docker_container:
      name: app-demo
      image: brunoguidone/app-demo:v1
      state: started
      restart: yes